# Generated by Django 3.2.9 on 2021-12-08 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=120, verbose_name='número')),
                ('process_class', models.CharField(max_length=120, verbose_name='classe')),
                ('subject', models.CharField(max_length=120, verbose_name='assunto')),
                ('judge', models.CharField(max_length=120, verbose_name='assunto')),
            ],
            options={
                'verbose_name': 'processo',
                'verbose_name_plural': 'processos',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('category', models.CharField(max_length=120, verbose_name='categoria')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.process', verbose_name='processo')),
            ],
            options={
                'verbose_name': 'parte',
                'verbose_name_plural': 'partes',
                'ordering': ('-pk',),
            },
        ),
    ]
